### ISSUE TITLE
Upgrade to latest Tendermint (v0.16+)

### ISSUE THREAD

**Issue by ebuchman** [keppel/lotion#102]
v0.16 has significant changes to the peering layer that fix a lot of issues.

The most important thing to note is that peer addresses now require a node ID, which can be found using the `tendermint show_node_id` command. Ie. the addresses should look like `ID@IP:PORT`.

You can remove the need for the ID by setting `p2p.auth_enc = false` though it's not recommended. 

In any case, there are lots of bug fixes in that release that would be good to inherit. There's also a number of changes to ABCI that will need to be updated for. 

The v0.17 upgrade is quite minimal in comparison.

Prompted by https://github.com/tendermint/tendermint/issues/1397#issuecomment-377723994 which I'm hoping is fixed since v0.16

**Comment by keppel** [comment]
Done, thanks!
