### ISSUE TITLE
Adding New Validators via chainInfo results in consensus panic upon restart

### ISSUE THREAD

**Issue by a13xander96** [keppel/lotion#127]
I'm trying to add validators via chainInfo objects by simply mutating the chainInfo objects:

chainInfo.validators[newValidatorKey] = 1;

At first the transaction went through, and i can check from tendermint/dump_consensus_state that newValidatorKey is now a validator, with correct address and everything.

The Data is like this:

newValidatorKey is '01E6359CB91ECB34FD1836255B319E0AE11B7CA209A53CA8F1A00109AA8AE2810A'

and its address is '7A41C638443B70D6D4C199E9AF50F44F683415F3'

all this data is taken from a keys.json file

The issues begin when restarting one of the node, resulting in consensus error listed below

`E[05-17|15:33:15.985] Error attempting to add vote                 module=consensus err="Cannot find validator 3 in valSet of size 3: Invalid validator index"
E[05-17|15:33:15.989] Error attempting to add vote                 module=consensus err="vote.ValidatorAddress (37413431433633383434334237304436443443313939453941463530463434463638333431354633) does not match address (C905F3497237189AD3F382071E2646B3F5ADB66A) for vote.ValidatorIndex (2): Invalid validator address"`

Before Restarting, tendermint/dump_consensus_state shows validators added successfuly

`"validators": [
          {
            "address": "260FA49B51177F1B08C6BA61B820C2D8A65F5539",
            "pub_key": {
              "type": "ed25519",
              "data": "A39EB8A28A694E92C89A48F0B18DF2AD60289EF8168E0A398979DEC80D418662"
            },
            "voting_power": 3,
            "accum": -7
          },
          {
            "address": "6D12CE12A2CF08A21DABD058ED8FA54495E393CB",
            "pub_key": {
              "type": "ed25519",
              "data": "B97FD085F6FB81AF886AFD4A4D8742A7814BFC566DE33C85C5F326E1EE9E019F"
            },
            "voting_power": 10,
            "accum": 3
          },
          {
            "address": "7A41C638443B70D6D4C199E9AF50F44F683415F3",
            "pub_key": {
              "type": "ed25519",
              "data": "E6359CB91ECB34FD1836255B319E0AE11B7CA209A53CA8F1A00109AA8AE2810A"
            },
            "voting_power": 1,
            "accum": 2
          },
          {
            "address": "C905F3497237189AD3F382071E2646B3F5ADB66A",
            "pub_key": {
              "type": "ed25519",
              "data": "BC97580DD6395FCDA332A161BEF3B8279AEFABAB67D99BE4033C59B42D419CB6"
            },
            "voting_power": 5,
            "accum": 2
          }
        ],`

Is this a bug or am i doing this incorrectly? thanks

**Comment by keppel** [comment]
This should be fixed now!
