### ISSUE TITLE
unable to distinguish checkTx() or deliverTx() ABCI calls in useTx() handler

### ISSUE THREAD

**Issue by johannbarbie** [keppel/lotion#131]
I have a use-case that requires a list of all included transactions when a block is committed (`useBlock()` called). My use-case checkpoints each block in another chain with a custom Merkle implementation.

This transaction data is not passed. Also i'm unable to aggregate a list of transactions in the `useTx()` handler as it has no way to distinguish if the `checkTx()` or `deliverTx()` ABCI methods are called. A transaction could have been added to the mempool, without being included in the block.

plz help :)

**Comment by johannbarbie** [comment]
i would suggest to include a flag in the `useTx()` handler interface. then i can build a list of included transactions myself. Is there a better way?

**Comment by keppel** [comment]
hey Johann!

mutations to the `state` object get rolled back after a `checkTx`, so if you do something like this:

```js
let lotion = require('lotion')

let app = lotion({
  initialState: {
    transactions: []
  }
})

app.use(function(state, tx) {
  state.transactions.push(tx)
})

app.useBlock(function(state) {
  console.log(state.transactions)
})

app.listen(3000)
```

then `state.transactions` should contain what you'd expect in the `useBlock` handler (that is: only transactions that have made it into a block).

**Comment by johannbarbie** [comment]
cool, that is good to know.
am i right, that the state is kept in memory, and hence should be kept small. if i keep a list of all transactions in the state, it will soon slow down the node.

could i remove the list of transaction in the `useBlock()` call from the state again, to prevent the state from bloating?

**Comment by johannbarbie** [comment]
confirmed that accumulation of transactions is possible. thanks for the hint again @keppel . issue resolved.
