### ISSUE TITLE
`createEmptyBlocks: false` has no effect on the node start

### ISSUE THREAD

**Issue by johannbarbie** [keppel/lotion#134]
reason being, that the node will be started with 
`--consensus.create_empty_blocks false`
instead of
`--consensus.create_empty_blocks=false`

**Comment by johannbarbie** [comment]
dirty workaround in `lib/tendermint.js`
```
  if (createEmptyBlocks === false) {
    opts.consensus = {};
    opts.consensus['create_empty_blocks=false'] = false;
  }
```

which works because it produces:
`--consensus.create_empty_blocks=false false`

**Comment by mappum** [comment]
Strange, is `create_empty_blocks` parsed differently than the other flags in Tendermint? Because the others work as `--<flag> <value>`.

**Comment by johannbarbie** [comment]
i guess there are bool and string flags: 
https://github.com/tendermint/tendermint/blob/c84be3b8ddf46040567897f7d8163d35aa561a25/cmd/tendermint/commands/run_node.go#L39-L42

**Comment by mappum** [comment]
Ah, makes sense. I'll change `tendermint-node` to always use `--<flag>=<value>`.
