### ISSUE TITLE
Mempool state should persist between CheckTx calls

### ISSUE THREAD

**Issue by mappum** [keppel/lotion#136]
We're currently rolling back the mempool state after each `CheckTx`, but that lets attackers create unlimited spam transactions without incurring any fees. (Transactions may all be valid on their own, but invalid if any one of them is committed).

We should be mutating a temporary mempool state for each `CheckTx` call, then rolling it back at `BeginBlock`. This way, subsequent mempool txs will be invalid after the first one which pays the fee, so nodes will reject any spam transactions that won't end up paying fees.

The mempool state might be different than other nodes since `CheckTx`s aren't guaranteed to be delivered in the same order as other nodes, but that's OK.

**Comment by keppel** [comment]
Done! (In [lotion-state-machine](https://github.com/keppel/lotion-state-machine))
