### ISSUE TITLE
Problem running new Hello world App

### ISSUE THREAD

**Issue by raheelkhokhar** [keppel/lotion#146]
Hello guys, I am new to lotion js and blockchain.

I am on Windows 10. I am using Ubuntu terminal for Windows (installed as Windows store app). I am using node vesion 10.7. Installed lotion js using NPM. After creating app, when I run application using "app.js", it shows me command prompt on next line. No error occurs. Nothing runs.

Please help.

```const lotion = require('lotion');
let app = lotion({
    initialState: {
        count: 0
    }
});
app.listen(3000, function () {
    console.log("Express server listening on port 3000");
});

**Comment by keppel** [comment]
Hey @raheelkhokhar,

If you're still interested in trying this out, have a look at [https://lotionjs.com/getting-started.html](https://lotionjs.com/getting-started.html)!
