### ISSUE TITLE
Static GCI 

### ISSUE THREAD

**Issue by IncentiveLoop** [keppel/lotion#152]
It looks like the GCI of a node should be static because it is just the hash of the [genesis.json file](https://github.com/keppel/lotion/blob/dddb8ff806692b6b44c6d8c797bc0a9cd80daec8/src/index.ts#L80), however the GCI appears to change each time a node is restarted for some reason. This can be a bit of a hassle for testing.

**Comment by hackable** [comment]
Have not been able to produce a static cgi even after setting genesis file

**Comment by keppel** [comment]
@hackable can you post the options object that you’re passing to `lotion()` please? are you on lotion@0.4.8?

**Comment by hackable** [comment]
Yes im on     "lotion": "^0.4.8"
`
lotion({
  initialState: {
    blockNo: 0,
		txCount: 0
  },
  genesisPath: 'genesis.json'
})
`
