### ISSUE TITLE
Multinode local network setup example

### ISSUE THREAD

**Issue by IncentiveLoop** [keppel/lotion#153]
It would be great to have the docs outline how to quickly setup a local network to test your chain.

If you point me in the right direction so that I can achieve this myself I would be happy to make a docs PR.

**Comment by ameeuw** [comment]
Hi @IncentiveLoop - I just created an example version which works with the current develop branch of lotion. I created a pull request for the develop branch but until it is merged into the actual version, you can just add the files or clone the `develop_example` branch from my fork (github.com/ameeuw/lotion).

Do an npm install and then run `run_node0.sh` and `run_node1.sh` in two separate terminal windows. If you want to restart the chains, delete the created network files in `$home/.lotion/networks`.

**Comment by mjackson001** [comment]
this works, but need to edit app.js and change the IP address to 127.0.0.1 first
