### ISSUE TITLE
Connecting to other nodes doesnt work 

### ISSUE THREAD

**Issue by uWinkel** [keppel/lotion#156]
Hi, so I tried to build a simple blockchat which doesnt use the GCI but the lotion connect method You can check it out [here](https://github.com/uWinkel/ltblockchat)

It works fine on one node but when connecting to other nodes I still run into problems. You can see the tendermint log [here](https://pastebin.com/yL9RydMW)

I have tried adding the nodes with id@ip as seeds in config.toml but this didnt work either.

also I have allowed for the these ports to be open on both (ubuntu) machines
26656 26657 46656  46657  3000

is there anything I can do to fix this and let the nodes connect with each other? Any help would be great!

**Comment by keppel** [comment]
Cool app! This might just work on the newest release of Lotion, but if not, you might want to try adding your peer IDs on `opts.peers` [here](https://github.com/uWinkel/ltblockchat/blob/master/chat-node.js#L18)!
