### ISSUE TITLE
when lotion.start() execute, occur exception

### ISSUE THREAD

**Issue by pjt3591oo** [keppel/lotion#162]
https://github.com/keppel/lotion/blob/develop/src/tendermint.ts#L122

why is this line need?

when lotion.start() execute, occur exception

**Comment by keppel** [comment]
Hey @pjt3591oo!

The `tendermintProcess` promise only resolves if the Tendermint process exits, which we don't really expect to happen during a Lotion app's lifetime unless something goes wrong, so it's an error.
