### ISSUE TITLE
the ‘latest_block_height’ in http://localhost:49932/status keep increasing 

### ISSUE THREAD

**Issue by terrorgeek** [keppel/lotion#168]
Hi guys, 

  As I running the sample application it's working but when I accessed 'http://localhost:49932/status', every time I refresh the browser the 'latest_block_height' under 'sync_info' is increased but I didn't insert any transaction or block.  
  I also found that 'latest_block_height' is increasing 1 by each second. 

  Is there anyone can tell me why? and how can I add a block by myself with bunch of customized transactions in it using LotionJS? Thanks a lot.

below are the entire json if you access to 
http://localhost:49932/status,   49932 is the RPC port which changes everytime I start the Lotion sample app.

{
"jsonrpc": "2.0",
"id": "",
"result": {
"node_info": {
"id": "f3b6d7a14a90806fddc36bbb3b48cfe84d937576",
"listen_addr": "tcp://0.0.0.0:49931",
"network": "test-chain-sBgm0s",
"version": "0.25.0-0c9c3292",
"channels": "4020212223303800",
"moniker": "ip-192-168-0-102.ec2.internal",
"other": {
"amino_version": "0.12.0",
"p2p_version": "0.5.0",
"consensus_version": "v1/0.2.2",
"rpc_version": "0.7.0/3",
"tx_index": "on",
"rpc_address": "tcp://0.0.0.0:49932"
}
},
"sync_info": {
"latest_block_hash": "6B02E6534C5C3E73555C2881D0C1D3474C1C8F28",
"latest_app_hash": "618DE7D9F46F3F697D827A1B6D84974760D5DEDA62E4E592ADAA3C646602A94C",
"latest_block_height": "112",
"latest_block_time": "2019-02-23T15:25:02.757674316Z",
"catching_up": false
},
"validator_info": {
"address": "36522C242E0D88118543345050B4550B6D4C4097",
"pub_key": {
"type": "tendermint/PubKeyEd25519",
"value": "vvFdLLr/Me55RpSuQxslt/x1d90W65lZcqKmBpowluY="
},
"voting_power": "10"
}
}
}

**Comment by keppel** [comment]
Hey @painforever 

Right, Tendermint creates new blocks about once per second by default, even if there aren't any new transactions. If you'd like to dig deeper into what's going on under the hood, the [Tendermint documentation](https://tendermint.com/docs/) is a very interesting read.

As far as creating your own Transactions, use the `send` method on the light client instance returned by `lotion.connect()`
