### ISSUE TITLE
curl hang

### ISSUE THREAD

**Issue by ericbets** [keppel/lotion#39]
So I had app.js running and peer.js running in another term:

I tried curl http://localhost:3000/state in another term window and this is what showed up in the first window:

node app.js 
(node:15154) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): Error: Request failed with status code 500
(node:15154) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by keppel** [comment]
hey Eric, thanks again for the report!

how are you running the examples? did you clone the repo and `npm i` or just copy the code from `app.js` and `peer.js` locally? if it's the latter, make sure you also grabbed the example genesis and key files.

if you cloned the repo, which branch are you running the examples on? I can't seem to re-create the issue on `master`

**Comment by ericbets** [comment]
I just did an npm rebuild and cd'd into the directory.

**Comment by keppel** [comment]
latest release upgraded the Tendermint version, wanna do a quick npm install and see if it works? 

Tendermint gets downloaded in the install script, so I don't think a rebuild would update it.

if that doesn't fix everything, would recommend cloning the repo again, npm install, then run the examples.

**Comment by ericbets** [comment]
yep, that worked cheers
