### ISSUE TITLE
How can I specify a config.toml?

### ISSUE THREAD

**Issue by Jaxkr** [keppel/lotion#50]
I cannot figure out how to specify a config.toml for a lotion app. I've tried placing the file in both ~/.lotion and the /bin directory containing Tendermint, but both seem to have been ignored.

**Comment by keppel** [comment]
hmm, currently there's not really a way to do that!

probably most things you'd put in the config.toml, I'd rather support on the `opts` object. like, if you're trying to change the interval between blocks, maybe that's in `opts.consensus.blockInterval`, then specify them as command line arguments on `tendermint node` (like you just added in your createEmptyBlocks pr).

just curious, what're you tryna do in your config.toml?

**Comment by Jaxkr** [comment]
Does every config.toml option has a corresponding command line flag? I actually wanted to implement your example. :)
I tried using `--consensus.create_empty_blocks_interval` and was met with `ERROR: unknown flag: --consensus.create_empty_blocks_interval`. However, I could have been using the wrong flag.

Because if everything has a flag, then there is no need for config.toml support.

**Comment by keppel** [comment]
mm yeah, looks like that does actually need to come from the config.toml, there's no command line flag for that. we can add `opts.consensus.createEmptyBlocksInterval` then write the config.toml in `initNode` in `lib/tendermint.js`

**Comment by Jaxkr** [comment]
Alright, sounds great. I'll look into implementing that.

**Comment by keppel** [comment]
amazing, stoked to have you involved Jackson!

feel free to jump in [here](https://join.slack.com/t/lotion/shared_invite/enQtMjgzMjYyOTU4MzI3LWY2NTRlOGEwMGMwOTM0ODYxMjJkYWU1ZjZhZjI5MzE4NzllZWYwNzZlNzQ5MTk2ZTY5NWVkMjg2OGY4YWUzODU) if you wanna chat about it :)
