### ISSUE TITLE
Is it possible to have multiple nodes on one computer communicate?

### ISSUE THREAD

**Issue by Jaxkr** [keppel/lotion#51]
Interested in testing the functionality of an experimental app with multiple Tendermint nodes with running lotion node processes on a single computer. Is this possible?

**Comment by Jaxkr** [comment]
Nevermind. I've figured it out. All that is necessary is to set a different lotion home directory for any additional nodes.

**Comment by keppel** [comment]
sweet, yeah. it should automatically use a different lotion home if you set `opts.devMode = true`.
