### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by yousifucv** [keppel/lotion#58]
When running the code on the ReadMe I get: 

_C:\Users\Yousif\Documents\Dev\my-block-chain-app>node app.js
(node:5824) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, open 'C:\Users\Yousif\.lotion\networks\f0de10af52caa20754575a42899e005c7cb48f461219042bc43cffd614934863\genesis.json'
(node:5824) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code._

Running Node 8.7.0. Windows 8 64-bit
There is no .lotion directory under my home directory.
I tried this in Git Bash and my Command Prompt, and I also tried my command prompt under admin privileges.

**Comment by uglymaann** [comment]
Same. Even with the correct version and update:
linaro@linaro-alip:~/crypto$ npm update lotion
linaro@linaro-alip:~/crypto$ node app.js

I always end up geting:
(node:5578) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/home/linaro/.lotion/networks/3a91eebafd576ab5eead3ecf2deb3e4c2310bfbc69d4025d7503b227891f2a5a/genesis.json'
    at Object.fs.openSync (fs.js:663:18)
    at Object.fs.readFileSync (fs.js:568:33)
    at Promise (/home/linaro/crypto/node_modules/lotion/lib/tendermint.js:51:21)
    at <anonymous>
(node:5578) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5578) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Are you using windows or mac? If you're using windows, I think it has a dependency that makes it only work on mac. Forcing the install causes errors when it loads up. even with sudo su

**Comment by keppel** [comment]
thanks for the report! correct, this isn't working on windows at the moment, will try to fix it soon.

**Comment by binora** [comment]
Hi, I'm not able to run this on mac as well. Just followed the instructions as per README.MD.

**Comment by hmendes00** [comment]
same here.. any updates on it? thanks.

**Comment by vieiralc** [comment]
@hmendes00  I think it's not working on windows, try to use on ubuntu or mac

**Comment by koussakhan** [comment]
Getting this problem on Mac too!
`(node:1293) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)`
