### ISSUE TITLE
/state, /info and /txs endpoints do not have CORS headers, however all /tendermint endpoints do.

### ISSUE THREAD

**Issue by Jaxkr** [keppel/lotion#61]
I cannot GET /state, /info nor /txs from a JavaScript client webpage. However, I can get all /tendermint passthrough endpoints.

Recommended fix: Add CORS headers to these endpoints. I will look into doing this.

**Comment by patrickwieth** [comment]
same problem here

**Comment by keppel** [comment]
awesome, thanks guys! I think @Jaxkr is working on changing this now 👍
