### ISSUE TITLE
[Question] Production process

### ISSUE THREAD

**Issue by AlexMog** [keppel/lotion#70]
Hello,
I have created some tests with Lotion, and I would like to know the process to finally use a production Blockchain instead of the "test-*" generated one.
(it's not to pass in production right now, jsute to understand how to do it)
I have no idea how to do this.

Thanks for the answers!

Best regards,
AlexMog.

**Comment by keppel** [comment]
I'll write up a little guide on this soon and some better tooling, but the gist of it is: you just need to make a `keys.json` and `genesis.json` (and tell your app where to find those files through `opts.keys` and `opts.genesis`)

for the `keys.json`, for now you can run `./node_modules/bin/tendermint gen_validator` and just take `address`, `priv_key`, and `pub_key` properties from that json.

for the `genesis.json`, you'll need to pick an initial validator set, get their pub keys from the above step, then change the relevant values in some example `genesis.json` such as [this one](https://github.com/llSourcell/sirajcoin/blob/master/genesis.json).

:)
