### ISSUE TITLE
Adding and Removing Validators

### ISSUE THREAD

**Issue by markwylde** [keppel/lotion#74]
Currently from reading the docs I can see you can change the voting power dynamically by mutating the `chainInfo.validators` object.

However is there a way to add/remove a validator?

I was thinking maybe this is possible using the tendermint rest api? If so, we could add an `app.validators` object.

```javascript
app.validators.push({
    "pub_key": {
    "type": "ed25519",
    "data": "BAA8FE961773E916FBE5DC4AB195F3DEB22FC9330D44880F1FC558EE71B8A47B"
  },
  "power": 10,
  "name": ""
})
```

Maybe this could encompass some of my findings from issue #73 too by adding a "blockLastSeen". 

```javascript
app.validators === [..., {
    "pub_key": {
    "type": "ed25519",
    "data": "BAA8FE961773E916FBE5DC4AB195F3DEB22FC9330D44880F1FC558EE71B8A47B"
  },
  "power": 10,
  "name": "",
  "blockLastSeen": 100
}]
```

If it's just not implemented yet, I'd be more than happy to if you can point me in the right direction.

**Comment by markwylde** [comment]
Just read the abci documentation, and saw the following in the README at the [endBlock](https://github.com/tendermint/abci/blob/master/README.md#endblock) section:

> #### EndBlock
>   * __Arguments__:
>     * `Height (int64)`: The block height that ended
>   * __Returns__:
>     * `ValidatorUpdates ([]Validator)`: Changes to validator set (set voting power to 0 to remove)
>     * `ConsensusParamUpdates (ConsensusParams)`: Changes to consensus-critical time/size parameters
>   * __Usage__:<br/>
>     Signals the end of a block.  Called prior to each Commit after all transactions. Validator set is updated with the result.
> 

So it looks like by setting the voting power to 0, you can remove a validator, which is awesome. I haven't confirmed if this works with lotion, but I can't see why not.

However, it doesn't look like the endBlock can handle new blocks. Maybe you can just add a new public key?

**Comment by keppel** [comment]
yep, you can just go 

```js
chainInfo.validators[newValidatorPubKey] = 10 // or whatever amount of voting power
```
to add a new validator or

```js
chainInfo.validators[oldValidatorPubKey] = 0
```

to remove them :)
