### ISSUE TITLE
Feature: Lotion logo/branding update proposal

### ISSUE THREAD

**Issue by spentak** [keppel/lotion#80]
**Logo Revision**
I would like to propose some modifications to the logo and branding for lotion to set it forward as a professional-quality framework that companies can feel comfortable using - at least at first glance visually.

I've attached some logos that we (Devslopes) have created for Lotion. Created by our VP of Product Evan Leong. I'd love to get your thoughts about the variants and look into possibly picking one 😄 

**Open Source LotionJS.com**
I would also like to propose open-sourcing lotionjs.com so we can actively develop on it. It would be the place where traffic gets directed and have documentation, tutorials etc. Me, and some other web developers on my team would LOVE to help build it out. Take it to the level you see on https://electronjs.org/ and other websites.

Might be cool to consider something more open-sourcey like lotionjs.io , lotion.io or something similar if that makes sense.

# Logo Samples
[Download Logo Samples](https://www.dropbox.com/s/m8t3vwvk09iwce7/Lotion%20Logo%20Concepts.pdf?dl=0)

**Comment by keppel** [comment]
these logos look great, thanks Evan! definitely gotta be one of the hexagons ;)

I'm down with open-sourcing lotionjs.com, will do soon! I'm satisfied with the current domain for now (*js.com worked for express)
