### ISSUE TITLE
Where has 'lotion-stake' gone?

### ISSUE THREAD

**Issue by ameeuw** [keppel/lotion#82]
There is a mention of 'lotion-stake' on the lotionjs.com website but it seems like the repository has been taken down. Are there any updates on this repository?

**Comment by keppel** [comment]
sorry about that! that repo will exist next week

**Comment by ameeuw** [comment]
Nice one - thank you. I am looking forward to getting an idea on the implementation and adapt and augment it! Great to be working with your stuff.
