### ISSUE TITLE
Empty items getting pushed into array with new version of lotion (0.1.13)

### ISSUE THREAD

**Issue by ameeuw** [keppel/lotion#83]
After updating my version of lotion I found empty items getting pushed into state arrays. 

I just altered the base example from the README and yield `null` valued elements in my array.

app.js:

```javascript
let lotion = require('lotion')

let app = lotion({
  initialState: {
    count: 0,
    elements: []
  }
})

app.use(function (state, tx) {
  if(state.count === tx.nonce) {
    state.count++;
    state.elements.push(tx.nonce);
  }
})

app.listen(3000)
```

`localhost:3000/state` after 2 transactions with increasing nonces:
 `{"count":2,"elements":[null,0,null,1]}`

So far I have not been able to make out what and where the causing changes are - @keppel: Do you have any clue what it could be?

best,
arne

**Comment by keppel** [comment]
hey Arne, thanks for the issue! this'll be fixed today, will release a new version with the fix. sorry for the delay.

basically, v0.1.13 changed the way we isolate state changes made during the checkTx ABCI call. the way we rollback state changes made during checkTx comes from [this module](https://github.com/mappum/merk) which wasn't properly reversing array mutations. prior to v0.1.13, we would just clone the entire state tree, mutate that during checkTx, check that the transaction mutated the state and didn't throw an error, then throw away the cloned state tree.

**Comment by ameeuw** [comment]
Thank you Judd for your explanation - I wasn't able to make out what was causing the null-values.
