### ISSUE TITLE
version 0.1.15 unstable. Error: Tendermint node crashed

### ISSUE THREAD

**Issue by SaifRehman** [keppel/lotion#90]
<img width="1005" alt="screen shot 2018-03-07 at 12 01 10 pm" src="https://user-images.githubusercontent.com/18755233/37080380-7998f808-21ff-11e8-94d7-83b6fd5191e7.png">

**Comment by SaifRehman** [comment]
fixed

**Comment by vieiralc** [comment]
I'll still getting this error

**Comment by SaifRehman** [comment]
@vieiralc  run rm -rf ~/.lotion

**Comment by vieiralc** [comment]
I tried that but it didn't work, it gives me the same error

**Comment by vieiralc** [comment]
@SaifRehman I'm getting this now: https://github.com/keppel/lotion/issues/98
