### ISSUE TITLE
not a issue but a feature

### ISSUE THREAD

**Issue by SaifRehman** [keppel/lotion#93]
Lotion apps can now be easily deployed in any cloud premise. Most importantly cloud supporting cloud foundry. It is just matter of cf push to deploy a whole blockchain with sexy frontend.
Read more about it in readme. 
link: https://github.com/SaifRehman/tendermint-chat-app
I will be soon writting a blog and hosting meetup in dubai regarding this. I have googled the entire internet, nobody was able to host a blockchain on cloud foundry, this is possible now with lotion/tendermint. Great job guys, i loved the tech!
@keppel

**Comment by keppel** [comment]
thanks Saif :)
