### ISSUE TITLE
Mobile / Browser Light Client?

### ISSUE THREAD

**Issue by veqtor** [keppel/lotion#94]
Can you somehow use browserify to build a in-webpage light client?

**Comment by keppel** [comment]
yes! the light client just needs to be broken out into a separate module to play nicely with browserify. the tendermint block header verification is all already browserify-compatible.

I can break out the lite client into a separate module so you can `require('lotion/lite')` in the browser and add a usage demo next week if this is a feature you're interested in using.

**Comment by veqtor** [comment]
Definitely! I'm trying to build a dapp based on in-browser light clients.

**Comment by veqtor** [comment]
Any updates?

**Comment by bradleat** [comment]
any progress on this front?

**Comment by bradleat** [comment]
or does https://github.com/keppel/lotion/pull/66 fix this?

**Comment by keppel** [comment]
browser-friendly light client: https://github.com/keppel/lotion-connect
