### ISSUE TITLE
priv_validator.json Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by vieiralc** [keppel/lotion#98]
I'm trying to run a simple example but I get the following error:

![image](https://user-images.githubusercontent.com/19657718/37794592-b02fda7e-2df0-11e8-98e4-ec48cd6d32b4.png)

"UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, open 'C:\Users\lucas.vieira\.lotion\networks\583c7041c2ce21ac5778207c08c3f4a755397364552927bea49218eb475f13e9412962989\priv_validator.json'
(node:6944) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js
process with a non-zero exit code."

here is my code:

```
options = {
    initialState: {
        count: 0
    },
    genesis: 'genesis.json',
    keys: 'keys2.json',
    peers: ['localhost:46661'],
    p2pPort: 46660,
    devMode: true
}

let app = require('lotion')(options)
  
app.use((state, tx) => {
    state.count++
})
  
app.listen(3001)
```

I'm using windows 10. Already tried to run `rm -rf ~/.lotion`

**Comment by SaifRehman** [comment]
let me check

**Comment by SaifRehman** [comment]
show me ur code

**Comment by SaifRehman** [comment]
check if your other app is working

**Comment by vieiralc** [comment]
@SaifRehman My other app?
